### ISSUE TITLE
feat: deciding mission on Android App

### ISSUE THREAD

**Issue by ellen7788** [SUAN4423/MapDungeon#20]
ランダムにお題を決める関数をAndroid上で作成する

- お題はひらがなで50音から1文字ランダムに選ぶ
- 次の文字は選ばれないようにする：を、ん、小文字(っ、ゅetc...)

## 議論の余地があるもの
- 濁音・半濁音 ex)`さ`の時に`座間市`を正解にするかどうか、正解にするなら濁音・半濁音も選ばれないようにする
- 直前に出た文字を出ないように設定するか否か ex)お題`あ`をクリアした後に、次のお題として`あ`が選ばれないようにするか否か

**Comment by ellen7788** [comment]
濁音・半濁音は区別しない
ゆえに濁音・半濁音も選ばれないことが望ましい

**Comment by wbelucky** [comment]
母数が少ない頭文字は出にくい
自分がいる位置によって, ほどよい距離の町名がでやすい
とかの調整もあり?
