### ISSUE TITLE
fix: ミッションが重複しないように修正

### ISSUE THREAD

**Issue by ellen7788** [SUAN4423/MapDungeon#36]
今はミッションをランダムに8個生成してるだけなのでミッションが重複する

重複するといろいろ面倒なので重複しないようにしたい

**Comment by suta88** [comment]
distinctにしたい、わかります

**Comment by ellen7788** [comment]
これsutaにお願いしたい

**Comment by suta88** [comment]
getRandomHiranaga()、要らないのではと思ったらそういえば重み付けしていたのを忘れてた

**Comment by suta88** [comment]
要素がdistinct8個になるまでgetRandomHiragana呼び続けても大丈夫かなあ

**Comment by suta88** [comment]
これ雑にやると重みが大きいものが左上にきやすくなるから、最後に順番シャッフルします

**Comment by suta88** [comment]
.shuffled()がMutableListじゃなくてListになってしまうので、missionCharsをMutableList<Char>からList<Char>にしてしまっても良い？

**Comment by ellen7788** [comment]
いいよ:+1:

**Comment by SUAN4423** [comment]
Listは中身が変更できなくなる可能性があるので、中身が書き換えられないのであればちょっと変更は保留してほしさあるかも(お題の上書きができなくなりそう)

**Comment by ellen7788** [comment]
`toMutableList()`つかおう

**Comment by suta88** [comment]
.shuffled().toMutableList()をしてmutableで返します
