### ISSUE TITLE
Which should we make app for Mobile or Web?

### ISSUE THREAD

**Issue by wbelucky** [SUAN4423/MapDungeon#6]
要件的にはWebでも十分(アプリ開いているときに位置情報が取れればいいので)

- このプロジェクトでKotlinを勉強したりするモチベがあるならKotlinのままで.
- みんながわかる技術スタックを用いるならReact + TypeScriptとかが丸い?

**Comment by SUAN4423** [comment]
Webだと巨大なデータベースが必要になりそう(ユーザのデータをサーバが保持しなければならないので)
アプリだとこの点それぞれの端末に保存してしまえば解決(一部ランキングに必要なデータ等はサーバに保存するとしても)

個人的には広告を見せてスキップとかそういうのをやりたいのでモバイルアプリケーションで続けたい

**Comment by wbelucky** [comment]
ok, でもWebサーバは作りたいが、ok?

**Comment by wbelucky** [comment]
（巨大なDBを無駄に扱いたいのでユーザーデータをDBにブチ込たいとは考えている。

オンライン機能を使って実績を載せるかどうかとかはオプショナルでもいいのかものね

**Comment by SUAN4423** [comment]
巨大なDB、どこで管理するのか問題
Webサーバはどちらにせよ必要になるだろうから作らねばだよね(ランキング、週間クエスト等々)
Webアプリケーションでも広告を見せてスキップ等の機能ができればまぁそちらでもよいと思っている(広告収入がどこに入るのかは知らないので自分向けに来るよう設定せねばならないが)

**Comment by wbelucky** [comment]
PlanetScaleとかある程度DBを無料で使わせてくれるサービスを使ってみたいと思っている.
Webアプリケーションの広告スキップはやりにくそうだよね. やっぱモバイルネイティブかな, その辺は.
